# Generated by Django 5.2.5 on 2025-10-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='previous_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
