# Generated by Django 5.2.5 on 2025-08-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='reason_for_loan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
