# Generated by Django 5.2.5 on 2025-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_add_status_field"),  # ✅ ye 0002 ke baad aayega
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pancard_number",
            field=models.CharField(
                max_length=20, unique=True, null=True, blank=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="aadhaar_number",
            field=models.CharField(
                max_length=20, unique=True, null=True, blank=True
            ),
        ),
    ]
