# Generated by Django 5.2.5 on 2025-09-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_managers_and_more'),
    ]

    operations = [
    ]
