# Generated by Django 5.2.5 on 2025-08-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_loanrequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='reason_for_loan',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
