# Generated by Django 5.2.5 on 2025-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pancard_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
