# Generated by Django 5.2.5 on 2025-09-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhaar_number',
            field=models.CharField(help_text='12-digit Aadhaar (digits only, spaces auto-formatted in UI)', max_length=12, unique=True),
        ),
    ]
