# Generated by Django 5.2.5 on 2025-10-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_loanrequest_previous_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='previous_status',
        ),
    ]
