# Generated by Django 5.2.5 on 2025-09-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_complaint_supportticket_cibilreport_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Hold', 'Hold'), ('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Deleted', 'Deleted')], default='Hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_against',
            field=models.CharField(blank=True, help_text='Email or User ID', max_length=255),
        ),
    ]
