# Generated by Django 5.2.5 on 2025-09-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_aadhaar_number'),
    ]

    operations = [
    ]


from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_aadhaar_number'),  # 👈 yahan tumhare last migration ka naam dalna
    ]

    operations = [
        migrations.AddField(
            model_name="applicantdetails",
            name="cibil_last_generated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicantdetails",
            name="cibil_generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                blank=True,
                null=True,
                related_name="generated_cibil_scores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
