# Generated by Django 5.2.5 on 2025-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_is_blocked_profile_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ("Hold", "Hold"),
                    ("Active", "Active"),
                    ("Deactivated", "Deactivated"),
                    ("Deleted", "Deleted"),
                ],
                default="Hold",
            ),
        ),
    ]
