# Generated by Django 5.2.5 on 2025-10-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_deleteduserlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_against',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aadhaar_number',
            field=models.CharField(help_text='12-digit Aadhaar', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pancard_number',
            field=models.CharField(help_text='ABCDE1234F', max_length=10, unique=True),
        ),
    ]
