# Generated by Django 5.2.5 on 2025-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_delete_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('loan_request', 'Loan Request Page'), ('dashboard_admin', 'Admin Dashboard'), ('dashboard_applicant', 'Applicant Dashboard'), ('dashboard_lender', 'Lender Dashboard'), ('profile_form', 'Profile Form'), ('edit_profile', 'Edit Profile'), ('review_profile', 'Review Profile'), ('edit_profile', 'Edit Profile'), ('partial_profile', 'Partial Profile'), ('view_profile', 'View Profile'), ('register', 'Register Page'), ('login', 'Login Page')], max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField(blank=True, null=True)),
                ('size', models.CharField(choices=[('small', 'Small (200x200)'), ('medium', 'Medium (400x250)'), ('big', 'Big (728x90 Banner)')], default='medium', max_length=20)),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('top', 'Top'), ('bottom', 'Bottom'), ('inline', 'Inside Content')], default='right', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
